# Generated by Django 4.1.3 on 2022-11-26 17:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0002_alter_useraccess_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='id')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(unique=True)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
