# Generated by Django 4.1.3 on 2022-11-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_managementuser_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagementUser',
        ),
    ]
