# Generated by Django 4.1.3 on 2022-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_delete_managementuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='id')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
