# Generated by Django 4.1.3 on 2022-11-27 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_managementuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementuser',
            name='access_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='management.useraccess'),
        ),
        migrations.AddField(
            model_name='payment',
            name='owner',
            field=models.ForeignKey(default='ba3979b7-6091-4071-84cc-e6f301718269', on_delete=django.db.models.deletion.CASCADE, to='management.managementuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managementuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
