# Generated by Django 4.1.3 on 2022-11-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_managementuser_access_level_payment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementuser',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
